
Welcome to Flask-PonyWhoosh's documentation!
============================================

 |PyPI Package latest release| |PyPI Package monthly downloads| |Test|

 This package integrate the amazing power of ``Whoosh`` with ``Pony ORM``
 inside ``Flask``. Source code and issue tracking at
 http://github.com/piperod/Flask-PonyWhoosh.


User's Guide
------------


.. toctree::
   :maxdepth: 2

   config
   whatsnew
   quickstart
   add_wildcards
   models
   queries
   signals
   contexts
   changelog
   




